name=brew
description=Homebrew package manager
platforms=linux
default=false
provides=brew
setup=linux:brew/setup.sh
map=linux:brew/bash/05-brew.bash|${HOME}/.config/bashrc.d/05-brew.bash|requires=bash
