name=mise
description=mise tool version manager
platforms=linux,windows
default=true
provides=mise
package=mise|apt:mise
package=mise|dnf:mise
package=mise|pacman:mise
package=mise|brew:mise
package=mise|winget:jdx.mise
package=mise|scoop:mise
map=linux:mise/bash/10-mise.bash|${HOME}/.config/bashrc.d/10-mise.bash|requires=bash
map=windows:mise/powershell/10-mise.ps1|$PROFILE\..\Profile.d\10-mise.ps1|requires=powershell
