name=oh-my-posh
description=Oh My Posh prompt
platforms=linux,windows
default=false
map=linux:oh-my-posh/oh-my-posh.config.json|${HOME}/.config/oh-my-posh/config.json
map=linux:oh-my-posh/bash/10-oh-my-posh.bash|${HOME}/.config/bashrc.d/10-oh-my-posh.bash|requires=bash
map=windows:oh-my-posh/oh-my-posh.config.json|$PROFILE\..\oh-my-posh.config.json
map=windows:oh-my-posh/powershell/10-oh-my-posh.ps1|$PROFILE\..\Profile.d\10-oh-my-posh.ps1|requires=powershell
package=oh-my-posh|apt:oh-my-posh
package=oh-my-posh|dnf:oh-my-posh
package=oh-my-posh|pacman:oh-my-posh
package=oh-my-posh|brew:oh-my-posh
package=oh-my-posh|mise:oh-my-posh
package=oh-my-posh|winget:JanDeDobbeleer.OhMyPosh
package=oh-my-posh|scoop:oh-my-posh
