name=scoop
description=Scoop package manager
platforms=windows
default=false
provides=scoop
setup=windows:scoop/setup.ps1
map=windows:scoop/powershell/05-scoop.ps1|$PROFILE\..\Profile.d\05-scoop.ps1|requires=powershell
