name=atuin
description=Atuin shell history
platforms=linux,windows
default=false
setup=linux:atuin/setup.sh
setup=windows:atuin/setup.ps1
package=atuin|apt:atuin
package=atuin|dnf:atuin
package=atuin|pacman:atuin
package=atuin|brew:atuin
package=atuin|mise:atuin
package=atuin|winget:Atuinsh.Atuin
package=atuin|scoop:atuin
