name=atuin
description=Atuin shell history
platforms=linux,windows
default=false
setup=linux:atuin/setup.sh
setup=windows:atuin/setup.ps1
map=linux:atuin/bash/50-atuin.bash|${HOME}/.config/bashrc.d/50-atuin.bash|requires=bash
map=windows:atuin/powershell/50-atuin.ps1|$PROFILE\..\Profile.d\50-atuin.ps1|requires=powershell
package=atuin|apt:atuin
package=atuin|dnf:atuin
package=atuin|pacman:atuin
package=atuin|brew:atuin
package=atuin|mise:atuin
package=atuin|winget:Atuinsh.Atuin
package=atuin|scoop:atuin
