name=git
description=Git configuration
platforms=linux,windows
default=true
package=git|apt:git
package=git|dnf:git
package=git|pacman:git
package=git|brew:git
package=git|mise:git
package=git|winget:Git.Git
package=git|scoop:git
map=linux:git/gitconfig|.gitconfig
map=windows:git/gitconfig|.gitconfig
